image: node:10-alpine # use nodejs v10 LTS
cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:
    - node_modules/

before_script:
  - sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
  - apk add ruby ruby-dev openssl-dev gcc g++ make zlib-dev git
  - gem install bundler
  - cp -rf _config_gitlab.yml _config.yml

pages:
  script:
    - bundle install
    - bundle exec jekyll build
    - mv _site public
    # - bundle exec htmlproofer ./_site --check-html
  artifacts:
    paths:
      - public
  only:
    - master
